image: docker:latest

variables:
  REPOSITORY_URL: 558247379009.dkr.ecr.us-east-2.amazonaws.com/assetapi
  SERVICE_NAME: assetapi
  CLUSTER_NAME: production
  REGION: us-east-2

services:
- docker:dind

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli

stages:
  - build

build:
  stage: build
  script:
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - echo "GOOSE";
    - $(aws ecr get-login --no-include-email --region $REGION)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
    - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment --region $REGION
  only:
    - master
  tags:
    - docker
