server:
  port: 8080

---

spring:
  profiles: default

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

cassandra:
  contactpoints: localhost

redis:
  hostname: localhost

---


spring:
  profiles: compose

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

cassandra:
  contactpoints: cassandra

redis:
  hostname: redis

---

spring:
  profiles: prod

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

cassandra:
  contactpoints: cassandra.internal.block16

redis:
  hostname: redis.internal.block16
