server:
  port: 8080

---

spring:
  profiles: default

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

redis:
  hostname: localhost

cassandra:
  contactpoints: localhost

---


spring:
  profiles: compose

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

redis:
  hostname: redis

cassandra:
  contactpoints: cassandra

---

spring:
  profiles: prod

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

redis:
  hostname: redis.internal.block16

cassandra:
  contactpoints: cassandra1.internal.block16,cassandra2.internal.block16,cassandra3.internal.block16
